#!/usr/bin/env node

/**
 * generate_readme.ts — Fetches profile-card.json from registered repos
 * and injects project cards into README.template.md → README.md.
 *
 * Zero dependencies. Node 18+ (native fetch).
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT_DIR = dirname(__dirname);

const REGISTRY_PATH = join(ROOT_DIR, "repos.json");
const TEMPLATE_PATH = join(ROOT_DIR, "README.template.md");
const OUTPUT_PATH = join(ROOT_DIR, "README.md");

const START_MARKER = "<!-- PROJECTS:START -->";
const END_MARKER = "<!-- PROJECTS:END -->";
const MAX_PROJECTS = 3;
const CARD_PATH = ".github/profile-card.json";

// ── types ──────────────────────────────────────────────

interface Logo {
    dark: string;
    light: string;
    alt: string;
}

interface ProfileCard {
    name: string;
    short_desc: string;
    long_desc?: string;
    logo: Logo;
    priority?: number;
    _repo?: string;
    _owner?: string;
}

interface Registry {
    owner: string;
    repos: string[];
}

// ── fetch ──────────────────────────────────────────────

async function fetchCard(
    owner: string,
    repo: string,
    branch = "main"
): Promise<ProfileCard | null> {
    const url = `https://raw.githubusercontent.com/${owner}/${repo}/${branch}/${CARD_PATH}`;

    try {
        const res = await fetch(url, {
            headers: { "User-Agent": "profile-readme-bot" },
        });

        if (res.status === 404) {
            console.log(`  ⊘ ${owner}/${repo}: no profile-card.json found, skipping.`);
            return null;
        }

        if (!res.ok) {
            console.log(`  ✗ ${owner}/${repo}: HTTP ${res.status}`);
            return null;
        }

        const data: ProfileCard = await res.json();
        data._repo = repo;
        data._owner = owner;
        return data;
    } catch (err) {
        console.log(`  ✗ ${owner}/${repo}: ${err}`);
        return null;
    }
}

// ── render ─────────────────────────────────────────────

function renderCard(card: ProfileCard): string {
    const owner = card._owner!;
    const repo = card._repo!;
    const repoUrl = `https://github.com/${owner}/${repo}`;
    const { name, short_desc, logo } = card;

    let html = `<table>
  <tr>
    <td width="30%">
      <a href="${repoUrl}">
        <picture>
          <source media="(prefers-color-scheme: dark)" srcset="${logo.dark}">
          <source media="(prefers-color-scheme: light)" srcset="${logo.light}">
          <img alt="${logo.alt}" src="${logo.dark}">
        </picture>
      </a>
    </td>
    <td width="70%">
      <b>${name}</b><br>
      ${short_desc}<br>
      <a href="${repoUrl}">view repository →</a>
    </td>
  </tr>
</table>`;

    const longDesc = card.long_desc?.trim();
    if (longDesc) {
        html += `

<details>
<summary>more on this ↓</summary>
<br>

${longDesc}

</details>`;
    }

    return html;
}

// ── main ───────────────────────────────────────────────

async function main() {
    const registry: Registry = JSON.parse(
        readFileSync(REGISTRY_PATH, "utf-8")
    );

    const { owner, repos } = registry;
    console.log(`scanning ${repos.length} repo(s) for ${owner}...`);

    // fetch all cards in parallel
    const results = await Promise.all(
        repos.map((repo) => fetchCard(owner, repo))
    );

    const cards = results
        .filter((c): c is ProfileCard => c !== null)
        .sort((a, b) => (a.priority ?? 99) - (b.priority ?? 99))
        .slice(0, MAX_PROJECTS);

    for (const card of cards) {
        console.log(`  ✓ ${card._owner}/${card._repo}: found '${card.name}'`);
    }

    console.log(`\n${cards.length} project(s) will be rendered (max ${MAX_PROJECTS}).\n`);

    // generate section
    let generated: string;
    if (cards.length === 0) {
        generated = [
            START_MARKER,
            "<!-- This section is auto-generated by scripts/generate_readme.ts. Do not edit manually. -->",
            "",
            "*no active projects right now.*",
            "",
            END_MARKER,
        ].join("\n");
    } else {
        generated = [
            START_MARKER,
            "<!-- This section is auto-generated by scripts/generate_readme.ts. Do not edit manually. -->",
            "",
            cards.map(renderCard).join("\n\n"),
            "",
            END_MARKER,
        ].join("\n");
    }

    // inject into template
    const template = readFileSync(TEMPLATE_PATH, "utf-8");
    const startIdx = template.indexOf(START_MARKER);
    const endIdx = template.indexOf(END_MARKER);

    if (startIdx === -1 || endIdx === -1) {
        console.error(`✗ Could not find markers in ${TEMPLATE_PATH}`);
        console.error(`  Expected: ${START_MARKER} and ${END_MARKER}`);
        process.exit(1);
    }

    const readme =
        template.slice(0, startIdx) +
        generated +
        template.slice(endIdx + END_MARKER.length);

    writeFileSync(OUTPUT_PATH, readme, "utf-8");
    console.log(`✓ README.md written to ${OUTPUT_PATH}`);
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
